import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/ui/sidebar";
import Navbar from "@/app/components/ui/navbar";
import Login from "@/app/login/page";
import { cookies } from "next/headers"; // Use Next.js headers to access cookies directly

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check the cookie directly on the server side using Next.js' `cookies()` function
  const cookieStore = cookies();
  // const authToken = cookieStore.get("authToken");
  const authToken = 'token'

  // If there is no authToken, redirect to the login page (can also render the login page directly here)
  if (!authToken) {
    // Redirect to the login page (use Next.js 13 routing)
    return (
      <div className="flex justify-center items-center min-h-screen bg-gray-100">
        <Login></Login>
      </div>
    );
  }

  // If authenticated, render the layout with sidebar and navbar
  return (
    <html lang="en">
      <body id="__next" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <div className="flex w-screen overflow-y-auto">
          <div className="bg-gray-200 flex-col w-48">
            <Sidebar />
          </div>
          <div className="flex-grow bg-gray-300 p-4 flex flex-col">
            <main className="flex-grow">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
